name: Main

on:
  push:
  pull_request:

jobs:
  Test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: fwal/setup-swift@v1
      #   with: { swift-version: "5.3.0" }
      - run: swift --version
      - run: swift test
